kind: Template
apiVersion: v1
metadata:
  name: "${APP_NAME}-pipeline-template"
objects:
  - kind: ProjectRequest
    apiVersion: v1
    metadata:
      name: "${NAMESPACE_BASE}-ci-cd"
  - kind: ProjectRequest
    apiVersion: v1
    metadata:
      name: "${NAMESPACE_BASE}-dev"
  - kind: ProjectRequest
    apiVersion: v1
    metadata:
      name: "${NAMESPACE_BASE}-stage"
  - kind: "BuildConfig"
    apiVersion: "build.openshift.io/v1"
    metadata:
      name: "${APP_NAME}-pipeline"
      namespace: ${NAMESPACE_BASE}-ci-cd
    spec:
      source:
        git:
          uri: "${SOURCE_REPOSITORY_URL}"
          ref: "master"
      strategy:
        jenkinsPipelineStrategy:
          JenkinsfilePath: Jenkinsfile
        type: JenkinsPipeline
parameters:
  - name: SOURCE_REPOSITORY_URL
    displayName: Source Repository URL
    description: The URL of the repository with your application source code
    required: true
  - name: APP_NAME
    displayName: App Name
    description: The name of the app which is being deployed
    required: true
  - name: NAMESPACE_BASE
    displayName: Namespace base name
    description: namespaces will be generated from this
    required: true